---
title: "summary"
output: html_document
date: "2022-12-05"
---
1. Although it is not very clear that there is a causal relationship between social media usage and mental health issues, there is an obvious correlational pattern between the two variables. This opens up the possibility that social media might lead to deteriorated mental health, while it could also go the other way around where mental health issues can lead to increased social media usage in seek of comfort, social approval, and company.

2. Going off of the previous point, an expected implication from this data analysis is that the increase in social media usage will eventually lead to worsening mental health issues from its basis. According to survey respondents from the Bangladesh dataset, many have reported that they feel anxious or depressed when interacting with social media for a long period of time or at all. Also, the more time people spend time on social media, they are easier to get influenced by others' posts, easier to feel depressed or hopeless, more often to have a poor appetite, worry more often, and have worse sleep quality. 

3. Young adults under the age of 25 are negatively impacted by social media. Drawing from background research, young adults are still developing their understanding of the world and how to build their social circle. Young adults today are born in the 21st century and grew up in an era of technology. According to this data analysis, young adults exhibit more social media usage on average and they are negatively impacted by inappropriate content online. Also, most young people spend roughly one more hour on social media compared to outdoor exercise. For young people who are developing physically, more time on social media and less time on exercises can be impactful on their health. 

